"""add_chat_logs_table

Revision ID: d7a583f9676b
Revises: b215e1353014
Create Date: 2026-02-17 19:08:22.330988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a583f9676b'
down_revision: Union[str, Sequence[str], None] = 'b215e1353014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thinking_text', sa.Text(), nullable=True),
    sa.Column('attachment_paths', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_logs_event_id'), 'chat_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_chat_logs_user_id'), 'chat_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_logs_user_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_event_id'), table_name='chat_logs')
    op.drop_table('chat_logs')
    # ### end Alembic commands ###
